import React from 'react';

/**
 * Renders HTML formatted text generated by contentEditable WYSIWYG editor safely.
 * Includes markdown fallbacks for backwards compatibility.
 */
export const parseMarkdown = (text?: string): React.ReactNode => {
  if (!text) return '';

  let html = text;

  // Fallback for markdown syntax if they typed it or loaded older files
  html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
  html = html.replace(/__(.*?)__/g, '<strong>$1</strong>');
  html = html.replace(/\*(.*?)\*/g, '<em>$1</em>');

  return <span dangerouslySetInnerHTML={{ __html: html }} />;
};
